### PR TITLE
FRENCH translation for Annual Stars extension

### PR DESCRIPTION
**Pull request by Galixte**
FRENCH translation for annualstars.php file

### CODE REVIEW

**Comment by Galixte** [comment]
Hi @tumba25,

could you take a look ?

**Comment by Galixte** [comment]
Hi @tumba25,

could you take a look ?

**Comment by Galixte** [comment]
Hi @bonelifer,

could you merge this, please ?

**Comment by bonelifer** [comment]
@Galixte Please sync your PR to current.

**Comment by Galixte** [comment]
Fixed here: https://github.com/phpbbmodders/phpbb-3.1-annualstars/pull/4.

**Pull request closed without merging**
